export const AREAS_LOAD = "AREAS_LOAD";
export const AREAS_LOAD_SUCCESSFUL = "AREAS_LOAD_SUCCESSFUL";
export const AREAS_LOAD_FAIL = "AREAS_LOAD_FAIL";

export const AREA_SELECT = "AREA_SELECT";
export const AREA_SELECT_SUCCESSFUL = "AREA_SELECT_SUCCESSFUL";
export const AREA_SELECT_FAIL = "AREA_SELECT_FAIL";

export const AREA_ADD = "AREA_ADD";
export const AREA_ADD_SUCCESSFUL = "AREA_ADD_SUCCESSFUL";
export const AREA_ADD_FAIL = "AREA_ADD_FAIL";

export const AREA_UPDATE = "AREA_UPDATE";
export const AREA_UPDATE_SUCCESSFUL = "AREA_UPDATE_SUCCESSFUL";
export const AREA_UPDATE_FAIL = "AREA_UPDATE_FAIL";

export const AREA_DELETE = "AREA_DELETE";
export const AREA_DELETE_SUCCESSFUL = "AREA_DELETE_SUCCESSFUL";
export const AREA_DELETE_FAIL = "AREA_DELETE_FAIL";
