export const NEXT_CLOUD_CREDENTIALS_LOGIN = "NEXT_CLOUD_CREDENTIALS_LOGIN";
export const NEXT_CLOUD_CREDENTIALS_LOGIN_SUCCESSFUL = "NEXT_CLOUD_CREDENTIALS_LOGIN_SUCCESSFUL";
export const NEXT_CLOUD_CREDENTIALS_LOGIN_FAIL = "NEXT_CLOUD_CREDENTIALS_LOGIN_FAIL";

export const NEXT_CLOUD_CREDENTIALS_LOGOUT = "NEXT_CLOUD_CREDENTIALS_LOGOUT";
export const NEXT_CLOUD_CREDENTIALS_LOGOUT_SUCCESSFUL = "NEXT_CLOUD_CREDENTIALS_LOGOUT_SUCCESSFUL";
export const NEXT_CLOUD_CREDENTIALS_LOGOUT_FAIL = "NEXT_CLOUD_CREDENTIALS_LOGOUT_FAIL";
