export const NEXT_CLOUD_CREDENTIALS_LOGIN: string = "NEXT_CLOUD_CREDENTIALS_LOGIN";
export const NEXT_CLOUD_CREDENTIALS_LOGIN_SUCCESSFUL: string = "NEXT_CLOUD_CREDENTIALS_LOGIN_SUCCESSFUL";
export const NEXT_CLOUD_CREDENTIALS_LOGIN_FAIL: string = "NEXT_CLOUD_CREDENTIALS_LOGIN_FAIL";

export const NEXT_CLOUD_CREDENTIALS_LOGOUT: string = "NEXT_CLOUD_CREDENTIALS_LOGOUT";
export const NEXT_CLOUD_CREDENTIALS_LOGOUT_SUCCESSFUL: string = "NEXT_CLOUD_CREDENTIALS_LOGOUT_SUCCESSFUL";
export const NEXT_CLOUD_CREDENTIALS_LOGOUT_FAIL: string = "NEXT_CLOUD_CREDENTIALS_LOGOUT_FAIL";
