export const LOAD_PERIODIC_TASKS = "LOAD_PERIODIC_TASKS";
export const SELECT_PERIODIC_TASK = "SELECT_PERIODIC_TASK";
export const ADD_PERIODIC_TASK = "ADD_PERIODIC_TASK";
export const UPDATE_PERIODIC_TASK = "UPDATE_PERIODIC_TASK";
export const DELETE_PERIODIC_TASK = "DELETE_PERIODIC_TASK";
