export const PERIODIC_TASKS_LOAD: string = "PERIODIC_TASKS_LOAD";
export const PERIODIC_TASKS_LOAD_SUCCESSFUL: string = "PERIODIC_TASKS_LOAD_SUCCESSFUL";
export const PERIODIC_TASKS_LOAD_FAIL: string = "PERIODIC_TASKS_LOAD_FAIL";

export const PERIODIC_TASK_SELECT: string = "PERIODIC_TASK_SELECT";
export const PERIODIC_TASK_SELECT_SUCCESSFUL: string = "PERIODIC_TASK_SELECT_SUCCESSFUL";
export const PERIODIC_TASK_SELECT_FAIL: string = "PERIODIC_TASK_SELECT_FAIL";

export const PERIODIC_TASK_ADD: string = "PERIODIC_TASK_ADD";
export const PERIODIC_TASK_ADD_LOCAL: string = "PERIODIC_TASK_ADD_LOCAL";
export const PERIODIC_TASK_ADD_ON_SERVER: string = "PERIODIC_TASK_ADD_ON_SERVER";
export const PERIODIC_TASK_ADD_SUCCESSFUL: string = "PERIODIC_TASK_ADD_SUCCESSFUL";
export const PERIODIC_TASK_ADD_FAIL: string = "PERIODIC_TASK_ADD_FAIL";

export const PERIODIC_TASK_UPDATE: string = "PERIODIC_TASK_UPDATE";
export const PERIODIC_TASK_UPDATE_ON_SERVER: string = "PERIODIC_TASK_UPDATE_ON_SERVER";
export const PERIODIC_TASK_UPDATE_SUCCESSFUL: string = "PERIODIC_TASK_UPDATE_SUCCESSFUL";
export const PERIODIC_TASK_UPDATE_FAIL: string = "PERIODIC_TASK_UPDATE_FAIL";

export const PERIODIC_TASK_DELETE: string = "PERIODIC_TASK_DELETE";
export const PERIODIC_TASK_DELETE_ON_SERVER: string = "PERIODIC_TASK_DELETE_ON_SERVER";
export const PERIODIC_TASK_DELETE_SUCCESSFUL: string = "PERIODIC_TASK_DELETE_SUCCESSFUL";
export const PERIODIC_TASK_DELETE_FAIL: string = "PERIODIC_TASK_DELETE_FAIL";
