export const PERIODIC_TASKS_LOAD = "PERIODIC_TASKS_LOAD";
export const PERIODIC_TASKS_LOAD_SUCCESSFUL = "PERIODIC_TASKS_LOAD_SUCCESSFUL";
export const PERIODIC_TASKS_LOAD_FAIL = "PERIODIC_TASKS_LOAD_FAIL";

export const PERIODIC_TASK_SELECT = "PERIODIC_TASK_SELECT";
export const PERIODIC_TASK_SELECT_SUCCESSFUL = "PERIODIC_TASK_SELECT_SUCCESSFUL";
export const PERIODIC_TASK_SELECT_FAIL = "PERIODIC_TASK_SELECT_FAIL";

export const PERIODIC_TASK_ADD = "PERIODIC_TASK_ADD";
export const PERIODIC_TASK_ADD_ON_SERVER = "PERIODIC_TASK_ADD_ON_SERVER";
export const PERIODIC_TASK_ADD_SUCCESSFUL = "PERIODIC_TASK_ADD_SUCCESSFUL";
export const PERIODIC_TASK_ADD_FAIL = "PERIODIC_TASK_ADD_FAIL";

export const PERIODIC_TASK_UPDATE = "PERIODIC_TASK_UPDATE";
export const PERIODIC_TASK_UPDATE_ON_SERVER = "PERIODIC_TASK_UPDATE_ON_SERVER";
export const PERIODIC_TASK_UPDATE_SUCCESSFUL = "PERIODIC_TASK_UPDATE_SUCCESSFUL";
export const PERIODIC_TASK_UPDATE_FAIL = "PERIODIC_TASK_UPDATE_FAIL";

export const PERIODIC_TASK_DELETE = "PERIODIC_TASK_DELETE";
export const PERIODIC_TASK_DELETE_ON_SERVER = "PERIODIC_TASK_DELETE_ON_SERVER";
export const PERIODIC_TASK_DELETE_SUCCESSFUL = "PERIODIC_TASK_DELETE_SUCCESSFUL";
export const PERIODIC_TASK_DELETE_FAIL = "PERIODIC_TASK_DELETE_FAIL";
