export const WIRELESS_SOCKETS_LOAD: string = "WIRELESS_SOCKETS_LOAD";
export const WIRELESS_SOCKETS_LOAD_SUCCESSFUL: string = "WIRELESS_SOCKETS_LOAD_SUCCESSFUL";
export const WIRELESS_SOCKETS_LOAD_FAIL: string = "WIRELESS_SOCKETS_LOAD_FAIL";

export const WIRELESS_SOCKET_SELECT: string = "WIRELESS_SOCKET_SELECT";
export const WIRELESS_SOCKET_SELECT_BY_ID: string = "WIRELESS_SOCKET_SELECT_BY_ID";
export const WIRELESS_SOCKET_SELECT_SUCCESSFUL: string = "WIRELESS_SOCKET_SELECT_SUCCESSFUL";
export const WIRELESS_SOCKET_SELECT_FAIL: string = "WIRELESS_SOCKET_SELECT_FAIL";

export const WIRELESS_SOCKET_ADD: string = "WIRELESS_SOCKET_ADD";
export const WIRELESS_SOCKET_ADD_LOCAL: string = "WIRELESS_SOCKET_ADD_LOCAL";
export const WIRELESS_SOCKET_ADD_ON_SERVER: string = "WIRELESS_SOCKET_ADD_ON_SERVER";
export const WIRELESS_SOCKET_ADD_SUCCESSFUL: string = "WIRELESS_SOCKET_ADD_SUCCESSFUL";
export const WIRELESS_SOCKET_ADD_FAIL: string = "WIRELESS_SOCKET_ADD_FAIL";

export const WIRELESS_SOCKET_UPDATE: string = "WIRELESS_SOCKET_UPDATE";
export const WIRELESS_SOCKET_UPDATE_ON_SERVER: string = "WIRELESS_SOCKET_UPDATE_ON_SERVER";
export const WIRELESS_SOCKET_UPDATE_SUCCESSFUL: string = "WIRELESS_SOCKET_UPDATE_SUCCESSFUL";
export const WIRELESS_SOCKET_UPDATE_FAIL: string = "WIRELESS_SOCKET_UPDATE_FAIL";

export const WIRELESS_SOCKET_DELETE: string = "WIRELESS_SOCKET_DELETE";
export const WIRELESS_SOCKET_DELETE_ON_SERVER: string = "WIRELESS_SOCKET_DELETE_ON_SERVER";
export const WIRELESS_SOCKET_DELETE_SUCCESSFUL: string = "WIRELESS_SOCKET_DELETE_SUCCESSFUL";
export const WIRELESS_SOCKET_DELETE_FAIL: string = "WIRELESS_SOCKET_DELETE_FAIL";
