export const LOAD_WIRELESS_SOCKETS = "LOAD_WIRELESS_SOCKETS";
export const SELECT_WIRELESS_SOCKET = "SELECT_WIRELESS_SOCKET";
export const ADD_WIRELESS_SOCKET = "ADD_WIRELESS_SOCKET";
export const UPDATE_WIRELESS_SOCKET = "UPDATE_WIRELESS_SOCKET";
export const DELETE_WIRELESS_SOCKET = "DELETE_WIRELESS_SOCKET";
