export const WIRELESS_SOCKETS_LOAD = "WIRELESS_SOCKETS_LOAD";
export const WIRELESS_SOCKETS_LOAD_SUCCESSFUL = "WIRELESS_SOCKETS_LOAD_SUCCESSFUL";
export const WIRELESS_SOCKETS_LOAD_FAIL = "WIRELESS_SOCKETS_LOAD_FAIL";

export const WIRELESS_SOCKET_SELECT = "WIRELESS_SOCKET_SELECT";
export const WIRELESS_SOCKET_SELECT_BY_ID = "WIRELESS_SOCKET_SELECT_BY_ID";
export const WIRELESS_SOCKET_SELECT_SUCCESSFUL = "WIRELESS_SOCKET_SELECT_SUCCESSFUL";
export const WIRELESS_SOCKET_SELECT_FAIL = "WIRELESS_SOCKET_SELECT_FAIL";

export const WIRELESS_SOCKET_ADD = "WIRELESS_SOCKET_ADD";
export const WIRELESS_SOCKET_ADD_LOCAL = "WIRELESS_SOCKET_ADD_LOCAL";
export const WIRELESS_SOCKET_ADD_ON_SERVER = "WIRELESS_SOCKET_ADD_ON_SERVER";
export const WIRELESS_SOCKET_ADD_SUCCESSFUL = "WIRELESS_SOCKET_ADD_SUCCESSFUL";
export const WIRELESS_SOCKET_ADD_FAIL = "WIRELESS_SOCKET_ADD_FAIL";

export const WIRELESS_SOCKET_UPDATE = "WIRELESS_SOCKET_UPDATE";
export const WIRELESS_SOCKET_UPDATE_ON_SERVER = "WIRELESS_SOCKET_UPDATE_ON_SERVER";
export const WIRELESS_SOCKET_UPDATE_SUCCESSFUL = "WIRELESS_SOCKET_UPDATE_SUCCESSFUL";
export const WIRELESS_SOCKET_UPDATE_FAIL = "WIRELESS_SOCKET_UPDATE_FAIL";

export const WIRELESS_SOCKET_DELETE = "WIRELESS_SOCKET_DELETE";
export const WIRELESS_SOCKET_DELETE_ON_SERVER = "WIRELESS_SOCKET_DELETE_ON_SERVER";
export const WIRELESS_SOCKET_DELETE_SUCCESSFUL = "WIRELESS_SOCKET_DELETE_SUCCESSFUL";
export const WIRELESS_SOCKET_DELETE_FAIL = "WIRELESS_SOCKET_DELETE_FAIL";
